rdjsite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include

import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('', include('site_forum.urls')),
]

site_forum/urls.py
from django.urls import path

from .views import views, ajax

app_name = 'forum'

urlpatterns = [
    path('', views.redirect_to_forum_view, name='index'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/register/', views.RegisterView.as_view(), name='register'),

    path('foruns/<slug:slug>/topicos/', views.TopicoView.as_view(), name='list_topico'),
    path('foruns/<slug:slug>/topicos/<int:topico_id>/', views.TopicoDetailView.as_view(), name='topico'),
    path('foruns/<slug:slug>/topicos/<int:topico_id>/respostas/', views.RespostaView.as_view(), name='resposta'),
    path('foruns/<slug:slug>/topicos/<int:topico_id>/respostas/<int:resposta_id>/', views.RespostaView.as_view(), name='detail_resposta'),

    path('ajax/topicos/', ajax.JSONTopicoView.as_view(), name='jax_topico'),
    path('ajax/respostas/', ajax.JSONRespostaView.as_view(), name='jax_resposta'),
]

site_forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

class TimeStampBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    class Meta:
        abstract = True

class Forum(TimeStampBase):
    nome = models.CharField(max_length=60)
    descricao = models.CharField(max_length=150)
    slug = models.SlugField(null=True, blank=True, unique=True)

    def get_absolute_url(self):
        return reverse('forum:list_topico', kwargs={'slug':self.slug})
    
    def save(self, *args, **kwargs):
        self.slug =slugify(self.nome)
        super(Forum, self).save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Topico(TimeStampBase):
    titulo = models.CharField(max_length=250)
    texto = models.TextField(blank=True)
    fechado = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('forum:topico', kwargs={'slug':self.forum.slug, 'topico_id':self.pk})
    
    def __str__(self):
        return self.titulo

class Resposta(TimeStampBase):
    texto = models.TextField(null=True, blank=True)
    parent = models.ForeignKey('Resposta', on_delete=models.CASCADE, null=True, blank=True)
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.user}-{self.pk}'

site_forum/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UsernameField
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django import forms

from site_forum.models import Resposta, Topico

class UserLoginForm(forms.Form):
    username = UsernameField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': (
            "Username %(username)s ou password incorretos."
        ),
    }
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            self._user = authenticate(username=username, password=password)

            if self._user is None:
                raise ValidationError(
                    self.error_messages['invalid_login'], 
                    code='invalid_login',
                    params={'username': username},)
            else:
                return cleaned_data
    
    def get_user(self):
        return self._user
            

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, initial='')
    password2 = forms.CharField(widget=forms.PasswordInput, initial='')

    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}
    
    def clean(self):
        cleaned_data = super().clean()
        password2 = cleaned_data.get('password2')
        password = cleaned_data.get('password')

        if password and password2 and (password != password2):
            self.add_error ('password2', ValidationError('Senhas diferentes'))
        else:
            return cleaned_data
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class TopicoCreateForm(forms.ModelForm):
    class Meta:
        model = Topico
        fields = ['titulo', 'texto']
    
    def save(self, user, forum, commit=True):
        topico = super().save(commit=False)
        topico.user = user
        topico.forum = forum
        if commit:
            topico.save()
        return topico

class TopicoUpdateForm(forms.ModelForm):
    class Meta:
        model = Topico
        fields = ['titulo', 'texto']


class RespostaForm(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = '__all__'
        exclude = ('user',)

    def save(self, user, commit=True):
        resposta = super().save(commit=False)
        resposta.user = user
        if commit:
            resposta.save()
        
        return resposta
        

site_forum/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.base import View
from django.views.generic.edit import FormView
from .models import Resposta, Topico, Forum
from .forms import RespostaCreateForm, UserRegisterForm, UserLoginForm, TopicoCreateForm

# Create your views here.

def redirect_to_forum_view(request):
    forum = Forum.objects.all().first()
    return redirect(forum)

@login_required
def logout_view(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER','/'))
    

class LoginView(FormView):
    template_name = 'site_forum/registration/login.html'
    form_class = UserLoginForm

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())
    
    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors()[0])
        return HttpResponseRedirect(self.request.path)
    
    def get_success_url(self):
        return self.request.GET.get('next', '/')

class RegisterView(FormView):
    template_name = 'site_forum/registration/register.html'
    success_url = '/'
    form_class = UserRegisterForm
    initial = {'username':''}

    def form_valid(self, form):
        login(request=self.request, user=form.save())
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, "Erro ao registrar o usuário!")
        return super().form_invalid(form)
        
class TopicoListView(ListView):

    queryset = Topico.objects
    context_object_name = 'topicos'
    template_name = 'site_forum/index.html'
    paginate_by = 15
    ordering = ['updated_at']

    def get_queryset(self):
        self.forum = get_object_or_404(Forum, slug=self.kwargs['slug'])
        return super().get_queryset().filter(forum=self.forum)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TopicoCreateForm
        context['foruns'] = Forum.objects.all()
        context['forum_atual'] = self.forum
        return context

class TopicoCreateView(View):

    def post(self, request, *args, **kwargs):
        form = TopicoCreateForm(request.POST)
        user = request.user
        forum = Forum.objects.get(slug=kwargs['slug'])

        if form.is_valid():
            topico = form.save(user, forum)
            return redirect(topico)
        else:
            return redirect(forum)


class RepostaListView(ListView):
    queryset = Resposta.objects.filter(deleted_at__isnull=True)
    context_object_name = 'respostas'
    template_name = 'site_forum/topico.html'
    paginate_by = 15
    ordering = ['created_at']

    def get_queryset(self):
        self.topico = get_object_or_404(Topico, pk=self.kwargs['topico_id'])
        return super().get_queryset().filter(topico=self.topico)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['forum_atual'] = get_object_or_404(Forum, slug=self.kwargs['slug'])
        context['foruns'] = Forum.objects.all()
        context['topico'] = self.topico
        return context

class RespostaCreateView(View):
    def post(self, request, *args, **kwargs):
        form = RespostaCreateForm(request.POST)
        user = request.user
        topico = Topico.objects.get(pk=kwargs['topico_id'])

        if form.is_valid():
            resposta = form.save(user)

        print(form.errors)

        return redirect(topico)

site_forum/views/ajax.py
from django.http import JsonResponse
from django.views.generic.base import View
from django.core.exceptions import ImproperlyConfigured
from django.http.response import HttpResponseNotFound
from site_forum.models import Resposta, Topico

class FilterMixin:
    filter_fields = []

    def get_queryset_filter(self, request):
        params = request.GET
        filter_dict = {}

        for key in set(params.keys()).intersection(set(self.filter_fields)):
            filter_dict[key] = params[key]
        
        return self.queryset.filter(**filter_dict)

class JSONMixin:
    fields = []
    data_name = 'data'

    def response_to_json(self, context):
        return JsonResponse(context)
    
    def get_data_json(self, queryset):
        data = []        
        for obj in list(queryset.values(*self.fields)):
            data.append(obj)
        
        return data

class JSONModelView(View, JSONMixin, FilterMixin):
    queryset = None

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            context = self.get_context_data(**kwargs)
            return self.response_to_json(context)
        else:
            return HttpResponseNotFound()
    
    def get_queryset(self, **kwargs):
        if self.queryset is None:
            raise ImproperlyConfigured('JSONModelview requer um queryset atributo.')

        queryset = self.get_queryset_filter(self.request)
        return queryset
    
    def get_context_data(self, **kwargs):
        queryset = self.get_queryset(**kwargs)
        data = self.get_data_json(queryset)
        context = {'count': len(data)}
        context[self.data_name] = data

        return context
    

class JSONTopicoView(JSONModelView):
    queryset = Topico.objects
    filter_fields = ['pk']
    fields = ['titulo', 'texto']

class JSONRespostaView(JSONModelView):
    queryset = Resposta.objects
    filter_fields = ['pk']
    fields = ['texto', 'parent__id']
        

site_forum/views/views.py
from django.http.response import HttpResponseForbidden, HttpResponseNotModified, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.base import View
from django.views.generic.edit import FormView

from site_forum.models import Resposta, Topico, Forum
from site_forum import forms
from site_forum.services import notifyservices

# Create your views here.

def redirect_to_forum_view(request):
    forum = Forum.objects.all().first()
    return redirect(forum)

@login_required
def logout_view(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER','/'))
    

class LoginView(FormView):
    template_name = 'site_forum/registration/login.html'
    form_class = forms.UserLoginForm

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())
    
    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors()[0])
        return HttpResponseRedirect(self.request.path)
    
    def get_success_url(self):
        return self.request.GET.get('next', '/')

class RegisterView(FormView):
    template_name = 'site_forum/registration/register.html'
    success_url = '/'
    form_class = forms.UserRegisterForm
    initial = {'username':''}

    def form_valid(self, form):
        login(request=self.request, user=form.save())
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, "Erro ao registrar o usuário!")
        return super().form_invalid(form)


class TopicoListView(ListView):

    queryset = Topico.objects
    context_object_name = 'topicos'
    template_name = 'site_forum/index.html'
    paginate_by = 15
    ordering = ['updated_at']

    def get_queryset(self):
        self.forum = get_object_or_404(Forum, slug=self.kwargs['slug'])
        return super().get_queryset().filter(forum=self.forum)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.TopicoCreateForm
        context['foruns'] = Forum.objects.all()
        context['forum_atual'] = self.forum
        return context

class TopicoCreateView(View):

    def post(self, request, *args, **kwargs):
        form = forms.TopicoCreateForm(request.POST)
        user = request.user
        forum = Forum.objects.get(slug=kwargs['slug'])

        if form.is_valid():
            topico = form.save(user, forum)
            return redirect(topico)
        else:
            return redirect(forum)

class TopicoView(View):
    def get(self, request, *args, **kwargs):
        view = TopicoListView.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = TopicoCreateView.as_view()
        return view(request, *args, **kwargs)


class TopicoUpdateView(View):

    def post(self, request, *args, **kwargs):
        topico = get_object_or_404(Topico, pk=kwargs['topico_id'])
        if topico.user != request.user:
            return HttpResponseForbidden()
        
        form = forms.TopicoUpdateForm(request.POST, instance=topico)
        if form.is_valid():
            form.save()
            return redirect(topico)
        
        return HttpResponseNotModified()

class TopicoRespostaListView(ListView):
    queryset = Resposta.objects.filter(deleted_at__isnull=True)
    context_object_name = 'respostas'
    template_name = 'site_forum/topico.html'
    ordering = ['created_at']

    def get_queryset(self):
        self.topico = get_object_or_404(Topico, pk=self.kwargs['topico_id'])
        return super().get_queryset().filter(topico=self.topico)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['forum_atual'] = get_object_or_404(Forum, slug=self.kwargs['slug'])
        context['foruns'] = Forum.objects.all()
        context['topico'] = self.topico
        return context


class TopicoDetailView(View):
    def get(self, request, *args, **kwargs):
        view = TopicoRespostaListView.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = TopicoUpdateView.as_view()
        return view(request, *args, **kwargs)


class RespostaView(View):
    def post(self, request, *args, **kwargs):
        user = request.user
        topico = Topico.objects.get(pk=kwargs['topico_id'])

        if kwargs.get('resposta_id'):
            resposta = get_object_or_404(Resposta, pk=kwargs['resposta_id'])
            form = forms.RespostaForm(request.POST, instance=resposta)

        else:
            form = forms.RespostaForm(request.POST)

        if form.is_valid():
            resposta = form.save(user)
            if not kwargs.get('resposta_id'):
                notifyservices.notify_answer(request, topico, resposta)
            
        return redirect(topico.get_absolute_url() + '#post' + str(resposta.pk))

site_forum/templates/site_forum/index.html
{% extends 'site_forum/base/base.html' %}
{% load static forum_tags %}

{% block title %}RespondeJunto{% endblock %}

{% block css %}
{{block.super }}
    <link href="{% static 'css/simplemde.min.css' %}" rel="stylesheet">
    <link href="{% static 'site_forum/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block extrahead%} {{block.super}}
    <script>
        MathJax = {
            tex: { inlineMath: [['$(', ')$']]},
            svg: { fontCache: 'global'}
        };
    </script>

    <script id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
{% endblock%}

{% block content %}
<main>
    <div class="container-fluid my-4">
        <div class="row gx-3 gy-3">

            <!--LEFT COLLUMN-->
            <div class="col-md-3 px-0 px-sm-1">
                <section class="forum-container">
                    <button class="btn-collapsible" type="button" data-bs-toggle="collapse" data-bs-target="#collapseForuns" aria-expanded="false" aria-controls="collapseForuns">
                        Foruns
                    </button>
                    <div class="collapse" id="collapseForuns">
                        <div class="list-group">
                        {% for forum in  foruns %}
                            {% if view.kwargs.slug == forum.slug %}
                            <a href="{{ forum.get_absolute_url}}" class="list-group-item fu-hover active">{{ forum }}</a>
                            {% else %}
                            <a href="{{ forum.get_absolute_url}}" class="list-group-item fu-hover">{{ forum }}</a>
                            {% endif %}
                        {% endfor %}
                        </div>
                    </div>
                </section>
            </div>

            <!--LEFT CENTER-->
            <div class="col-md-7 px-0 px-sm-1">
                <div class="add-post text-center p-2 fu-shadow">
                    <button class="fu-secondary-border" {% if user.is_authenticated %} data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" 
                        aria-controls="offcanvasBottom" {% else %} data-bs-toggle="modal" data-bs-target="#loginModal" {% endif %}>
                        
                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="currentColor">
                            <path d="M0 0h24v24H0z" fill="none"/>
                            <path d="M21 6h-2v9H6v2c0 .55.45 1 1 1h11l4 4V7c0-.55-.45-1-1-1zm-4 6V3c0-.55-.45-1-1-1H3c-.55 0-1 .45-1 1v14l4-4h10c.55 0 1-.45 1-1z"/></svg>
                        Criar um novo tópico?
                    </button>
                </div>

                <section class="container-topico pb-4">
                    <div class="forum_info pt-3 pb-4">
                        <h6 class="titulo-forum px-3">Forum: {{forum_atual}}</h6>
                        <p class="px-3"><small>{{forum_atual.descricao}}</small></p>
                    </div>

                    <table class="list-topico table align-middle">
                        <thead>
                            <tr class="text-center text-muted d-none d-sm-table-row">
                                <th colspan="2">Topicos</th>
                                <th>Respostas</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for topico in topicos %}
                            <tr>
                                <td width="30px" class="ps-sm-3">
                                    <div class="fu-user d-flex justify-content-center align-items-center">
                                        {{ topico.user.username|first|capfirst }} 
                                    </div>
                                </td>
                                <td class="ps-0">
                                    <a href="{{ topico.get_absolute_url }}" class="topico stretched-link">
                                        <div class="d-flex">
                                            <h5 class="topico-titulo">{{ topico }}
                                            {% if topico.categoria is not None %}
                                                <span class="badge bg-info">{{topico.categoria}}</span>
                                            {% endif %}
                                            </h5>
                                        </div>
                                        <div class="topico-footer d-flex flex-wrap">
                                            <span>Autor: {{ topico.user.username }}</span>
                                            <span class="ms-2 ms-sm-3">{{topico.updated_at|timesince}}</span>
                                        </div>
                                    </a>
                                </td>
                                <td width="10px" class="text-center">
                                    <span><b>{{topico.resposta_set.count}}</b></span>
                                </td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>

                    <nav aria-label="Page navigation">{% if page_obj.paginator.count > 0 %}
                        <ul class="pagination pagination-sm justify-content-center mt-5">
                            {% if page_obj.has_previous %}
                            <li class="page-item"> <a class="page-link" href="?page={{page_obj.previous_page_number}}">Anterior</a></li>{%else%}
                            <li class="page-item disabled"> <a class="page-link" href="">Anterior</a></li>{% endif %}
                
                            {% for p in page_obj|rangepage:5%}
                            <li class="page-item {%if p == page_obj.number %}active{% endif %}">
                                <a class="page-link" href="?page={{p}}">{{p}}</a>
                            </li> 
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item"> <a class="page-link" href="?page={{page_obj.next_page_number}}">Próximo</a></li>{%else%}
                            <li class="page-item disabled"> <a class="page-link" href="">Próximo</a></li>{% endif %}
                        </ul>{% endif %}
                    </nav>
                </section>
            </div>

            <!--LEFT RIGHT-->
            <div class="col-md-2 d-none d-sm-block">
                <section></section>
            </div>
        </div>
    </div>

    {# --=============== MODAIS PARA USUÁRIOS AUTENTICADOS ==============--> #}
    {% if user.is_authenticated %}
    <div class="offcanvas offcanvas-bottom offcanvas-post" tabindex="-1" id="offcanvasBottom"  aria-labelledby="offcanvasBottomLabel">
        <div class="offcanvas-header border">
            <h5 class="offcanvas-title" id="offcanvasBottomLabel">Criar um novo tópico?</h5>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <form class="form-topico" action="{% url 'forum:list_topico' forum_atual.slug %}" method="POST">
                {% csrf_token %}
                <div class="pb-2 d-flex flex-wrap">
                    <label for="input-titulo"> Titulo: </label>
                    <input class="flex-grow-1 ms-2 mb-2 mb-ms-0" id="input-titulo" name="titulo" required>
                </div>

                <div class="editor-container"> 
                    <textarea id="textareaPost" name="texto" required></textarea>
                </div>

                <div class="mt-2">
                    <button type="submit" class="btn btn-sm btn-primary d-block ms-auto">Criar tópico</button>
                </div>
            </form>
        </div>
    </div> {% endif%}

    {#--=============== MODAIS PARA USUÁRIOS NÃO AUTENTICADOS ==============--#}

    {% if not user.is_authenticated %}
    {% include "site_forum/base/login_modal.html" %}
    {% endif %}
</main>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/simplemde.min.js' %}"></script>
    
    <script>

        function initTextEditor() {
            const textarea = document.getElementById("textareaPost");
            
            if(textarea) {
                const simplemde = new SimpleMDE({ 
                    element: textarea,
                    spellChecker: false,
                    placeholder: "User tags html ou markdown",
                    hideIcons: ["image"],
                    status: false,
                    forceSync: true,
                    previewRender: function(plainText) {
                        let preview = document.getElementsByClassName("editor-preview-side")[0];
                        preview.innerHTML = this.parent.markdown(plainText);
                        preview.setAttribute('id','editor-preview')
                        MathJax.typeset([preview]);
                        return preview.innerHTML;
                    }
                });
            }
        }

        initTextEditor();

    </script>
{% endblock %}