rdjsite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include

import notifications.urls


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('', include('site_forum.urls')),
]

site_forum/urls.py
from django.urls import path

from .views import views, ajax

app_name = 'forum'

urlpatterns = [
    path('', views.redirect_to_forum_view, name='index'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/register/', views.RegisterView.as_view(), name='register'),

    path('foruns/<slug:slug>/topicos/', views.TopicoView.as_view(), name='list_topico'),
    path('foruns/<slug:slug>/topicos/<int:topico_id>/', views.TopicoDetailView.as_view(), name='topico'),
    path('foruns/<slug:slug>/topicos/<int:topico_id>/respostas/', views.RespostaView.as_view(), name='resposta'),
    path('foruns/<slug:slug>/topicos/<int:topico_id>/respostas/<int:resposta_id>/', views.RespostaView.as_view(), name='detail_resposta'),

    path('ajax/topicos/', ajax.JSONTopicoView.as_view(), name='jax_topico'),
    path('ajax/respostas/', ajax.JSONRespostaView.as_view(), name='jax_resposta'),
]

site_forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_NULL
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.

class TimeStampBase(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    class Meta:
        abstract = True

class Forum(TimeStampBase):
    nome = models.CharField(max_length=60)
    descricao = models.CharField(max_length=150)
    slug = models.SlugField(null=True, blank=True, unique=True)

    def get_absolute_url(self):
        return reverse('forum:list_topico', kwargs={'slug':self.slug})
    
    def save(self, *args, **kwargs):
        self.slug =slugify(self.nome)
        super(Forum, self).save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Topico(TimeStampBase):
    titulo = models.CharField(max_length=250)
    texto = models.TextField(blank=True)
    fechado = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('forum:topico', kwargs={'slug':self.forum.slug, 'topico_id':self.pk})
    
    def __str__(self):
        return self.titulo

class Resposta(TimeStampBase):
    texto = models.TextField(null=True, blank=True)
    parent = models.ForeignKey('Resposta', on_delete=models.CASCADE, null=True, blank=True)
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.user}-{self.pk}'

site_forum/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UsernameField
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django import forms

from site_forum.models import Resposta, Topico

class UserLoginForm(forms.Form):
    username = UsernameField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)

    error_messages = {
        'invalid_login': (
            "Username %(username)s ou password incorretos."
        ),
    }
    
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            self._user = authenticate(username=username, password=password)

            if self._user is None:
                raise ValidationError(
                    self.error_messages['invalid_login'], 
                    code='invalid_login',
                    params={'username': username},)
            else:
                return cleaned_data
    
    def get_user(self):
        return self._user
            

class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, initial='')
    password2 = forms.CharField(widget=forms.PasswordInput, initial='')

    class Meta:
        model = User
        fields = ('username',)
        field_classes = {'username': UsernameField}
    
    def clean(self):
        cleaned_data = super().clean()
        password2 = cleaned_data.get('password2')
        password = cleaned_data.get('password')

        if password and password2 and (password != password2):
            self.add_error ('password2', ValidationError('Senhas diferentes'))
        else:
            return cleaned_data
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class TopicoCreateForm(forms.ModelForm):
    class Meta:
        model = Topico
        fields = ['titulo', 'texto']
    
    def save(self, user, forum, commit=True):
        topico = super().save(commit=False)
        topico.user = user
        topico.forum = forum
        if commit:
            topico.save()
        return topico

class TopicoUpdateForm(forms.ModelForm):
    class Meta:
        model = Topico
        fields = ['titulo', 'texto']


class RespostaForm(forms.ModelForm):
    class Meta:
        model = Resposta
        fields = '__all__'
        exclude = ('user',)

    def save(self, user, commit=True):
        resposta = super().save(commit=False)
        resposta.user = user
        if commit:
            resposta.save()
        
        return resposta
        

site_forum/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.base import View
from django.views.generic.edit import FormView
from .models import Resposta, Topico, Forum
from .forms import RespostaCreateForm, UserRegisterForm, UserLoginForm, TopicoCreateForm

# Create your views here.

def redirect_to_forum_view(request):
    forum = Forum.objects.all().first()
    return redirect(forum)

@login_required
def logout_view(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER','/'))
    

class LoginView(FormView):
    template_name = 'site_forum/registration/login.html'
    form_class = UserLoginForm

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())
    
    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors()[0])
        return HttpResponseRedirect(self.request.path)
    
    def get_success_url(self):
        return self.request.GET.get('next', '/')

class RegisterView(FormView):
    template_name = 'site_forum/registration/register.html'
    success_url = '/'
    form_class = UserRegisterForm
    initial = {'username':''}

    def form_valid(self, form):
        login(request=self.request, user=form.save())
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, "Erro ao registrar o usuário!")
        return super().form_invalid(form)
        
class TopicoListView(ListView):

    queryset = Topico.objects
    context_object_name = 'topicos'
    template_name = 'site_forum/index.html'
    paginate_by = 15
    ordering = ['updated_at']

    def get_queryset(self):
        self.forum = get_object_or_404(Forum, slug=self.kwargs['slug'])
        return super().get_queryset().filter(forum=self.forum)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TopicoCreateForm
        context['foruns'] = Forum.objects.all()
        context['forum_atual'] = self.forum
        return context

class TopicoCreateView(View):

    def post(self, request, *args, **kwargs):
        form = TopicoCreateForm(request.POST)
        user = request.user
        forum = Forum.objects.get(slug=kwargs['slug'])

        if form.is_valid():
            topico = form.save(user, forum)
            return redirect(topico)
        else:
            return redirect(forum)


class RepostaListView(ListView):
    queryset = Resposta.objects.filter(deleted_at__isnull=True)
    context_object_name = 'respostas'
    template_name = 'site_forum/topico.html'
    paginate_by = 15
    ordering = ['created_at']

    def get_queryset(self):
        self.topico = get_object_or_404(Topico, pk=self.kwargs['topico_id'])
        return super().get_queryset().filter(topico=self.topico)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['forum_atual'] = get_object_or_404(Forum, slug=self.kwargs['slug'])
        context['foruns'] = Forum.objects.all()
        context['topico'] = self.topico
        return context

class RespostaCreateView(View):
    def post(self, request, *args, **kwargs):
        form = RespostaCreateForm(request.POST)
        user = request.user
        topico = Topico.objects.get(pk=kwargs['topico_id'])

        if form.is_valid():
            resposta = form.save(user)

        print(form.errors)

        return redirect(topico)

site_forum/views/ajax.py
from django.http import JsonResponse
from django.views.generic.base import View
from django.core.exceptions import ImproperlyConfigured
from django.http.response import HttpResponseNotFound
from site_forum.models import Resposta, Topico

class FilterMixin:
    filter_fields = []

    def get_queryset_filter(self, request):
        params = request.GET
        filter_dict = {}

        for key in set(params.keys()).intersection(set(self.filter_fields)):
            filter_dict[key] = params[key]
        
        return self.queryset.filter(**filter_dict)

class JSONMixin:
    fields = []
    data_name = 'data'

    def response_to_json(self, context):
        return JsonResponse(context)
    
    def get_data_json(self, queryset):
        data = []        
        for obj in list(queryset.values(*self.fields)):
            data.append(obj)
        
        return data

class JSONModelView(View, JSONMixin, FilterMixin):
    queryset = None

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            context = self.get_context_data(**kwargs)
            return self.response_to_json(context)
        else:
            return HttpResponseNotFound()
    
    def get_queryset(self, **kwargs):
        if self.queryset is None:
            raise ImproperlyConfigured('JSONModelview requer um queryset atributo.')

        queryset = self.get_queryset_filter(self.request)
        return queryset
    
    def get_context_data(self, **kwargs):
        queryset = self.get_queryset(**kwargs)
        data = self.get_data_json(queryset)
        context = {'count': len(data)}
        context[self.data_name] = data

        return context
    

class JSONTopicoView(JSONModelView):
    queryset = Topico.objects
    filter_fields = ['pk']
    fields = ['titulo', 'texto']

class JSONRespostaView(JSONModelView):
    queryset = Resposta.objects
    filter_fields = ['pk']
    fields = ['texto', 'parent__id']
        

site_forum/views/views.py
from django.http.response import HttpResponseForbidden, HttpResponseNotModified, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.generic import ListView
from django.views.generic.base import View
from django.views.generic.edit import FormView

from site_forum.models import Resposta, Topico, Forum
from site_forum import forms
from site_forum.services import notifyservices

# Create your views here.

def redirect_to_forum_view(request):
    forum = Forum.objects.all().first()
    return redirect(forum)

@login_required
def logout_view(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER','/'))
    

class LoginView(FormView):
    template_name = 'site_forum/registration/login.html'
    form_class = forms.UserLoginForm

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())
    
    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors()[0])
        return HttpResponseRedirect(self.request.path)
    
    def get_success_url(self):
        return self.request.GET.get('next', '/')

class RegisterView(FormView):
    template_name = 'site_forum/registration/register.html'
    success_url = '/'
    form_class = forms.UserRegisterForm
    initial = {'username':''}

    def form_valid(self, form):
        login(request=self.request, user=form.save())
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, "Erro ao registrar o usuário!")
        return super().form_invalid(form)


class TopicoListView(ListView):

    queryset = Topico.objects
    context_object_name = 'topicos'
    template_name = 'site_forum/index.html'
    paginate_by = 15
    ordering = ['updated_at']

    def get_queryset(self):
        self.forum = get_object_or_404(Forum, slug=self.kwargs['slug'])
        return super().get_queryset().filter(forum=self.forum)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.TopicoCreateForm
        context['foruns'] = Forum.objects.all()
        context['forum_atual'] = self.forum
        return context

class TopicoCreateView(View):

    def post(self, request, *args, **kwargs):
        form = forms.TopicoCreateForm(request.POST)
        user = request.user
        forum = Forum.objects.get(slug=kwargs['slug'])

        if form.is_valid():
            topico = form.save(user, forum)
            return redirect(topico)
        else:
            return redirect(forum)

class TopicoView(View):
    def get(self, request, *args, **kwargs):
        view = TopicoListView.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = TopicoCreateView.as_view()
        return view(request, *args, **kwargs)


class TopicoUpdateView(View):

    def post(self, request, *args, **kwargs):
        topico = get_object_or_404(Topico, pk=kwargs['topico_id'])
        if topico.user != request.user:
            return HttpResponseForbidden()
        
        form = forms.TopicoUpdateForm(request.POST, instance=topico)
        if form.is_valid():
            form.save()
            return redirect(topico)
        
        return HttpResponseNotModified()

class TopicoRespostaListView(ListView):
    queryset = Resposta.objects.filter(deleted_at__isnull=True)
    context_object_name = 'respostas'
    template_name = 'site_forum/topico.html'
    ordering = ['created_at']

    def get_queryset(self):
        self.topico = get_object_or_404(Topico, pk=self.kwargs['topico_id'])
        return super().get_queryset().filter(topico=self.topico)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['forum_atual'] = get_object_or_404(Forum, slug=self.kwargs['slug'])
        context['foruns'] = Forum.objects.all()
        context['topico'] = self.topico
        return context


class TopicoDetailView(View):
    def get(self, request, *args, **kwargs):
        view = TopicoRespostaListView.as_view()
        return view(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        view = TopicoUpdateView.as_view()
        return view(request, *args, **kwargs)


class RespostaView(View):
    def post(self, request, *args, **kwargs):
        user = request.user
        topico = Topico.objects.get(pk=kwargs['topico_id'])

        if kwargs.get('resposta_id'):
            resposta = get_object_or_404(Resposta, pk=kwargs['resposta_id'])
            form = forms.RespostaForm(request.POST, instance=resposta)

        else:
            form = forms.RespostaForm(request.POST)

        if form.is_valid():
            resposta = form.save(user)
            if not kwargs.get('resposta_id'):
                notifyservices.notify_answer(request, topico, resposta)
            
        return redirect(topico.get_absolute_url() + '#post' + str(resposta.pk))

site_forum/templates/site_forum/base/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
    {% block metadados %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% endblock %}
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="{% static 'site_forum/icon/favicon.ico' %}" type="image/x-icon">

    <title>{% block title %} {% endblock %}</title>

    {% block css %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   
    <link href="{% static 'site_forum/css/header-footer.css' %}" rel="stylesheet"> 
    {% endblock %}
    
    {% block extrahead %}{% endblock %}
</head>

<body>
    {% block header %} {% include 'site_forum/base/header.html' %} {% endblock %}

    {% block content %} {% endblock %}

    {% block footer %} {% include 'site_forum/base/footer.html' %} {% endblock %}

    {% block javascript %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script src="{% static 'site_forum/js/notifications.js'%}"></script>  
    {% endblock %}
</body>

</html>

site_forum/templates/site_forum/base/footer.html
<footer class="text-center">
    <small>&copy; Jelson Matheus | Todos os direitos reservados {% now 'Y' %}</small>
</footer>

site_forum/templates/site_forum/base/header.html
{%load static forum_tags notifications_tags %}
<header class="d-flex">
    <a href="/" class="logo">
        <object data="{% static 'site_forum/icon/logo.svg' %}" type="image/svg+xml">
            <img src="{% static 'site_forum/icon/logo.svg'%} " alt="logo">
        </object>
    </a>

    <div class="user-info">
        {% if user.is_authenticated %}

        <div class="btn-group">{% with notificacoes=user.notifications.unread  notificacoes_reads=user.notifications.read%} 
            <button class="btn notification position-relative me-3" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                    <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
                </svg>

                {% if notificacoes.count %}
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    {{notificacoes.count}}
                    <span class="visually-hidden">messagens não lidas</span>
                </span> {% endif %}
            </button> 

            <ul class="dropdown-menu menu-notificacao" aria-labelledby="dropdownNotification">
                <li><h6 class="dropdown-header">Notificações</h6></li>
                
                {% for notificacao in notificacoes %}
	            <li class="unread-notify" data-is-unread="{{notificacao.unread}}" data-slug="{{notificacao.slug}}">
                    <span class="circulo"><span class="visually-hidden">Nova notificação</span></span>
	                {{ notificacao|shownotify }} 		
		        </li> {% endfor %}

                {% if notificacoes_reads.count %}
                <li><hr class="dropdown-divider"></li>
                <li><h6 class="dropdown-header">Notificações lidas</h6></li>

                {% for notifi in notificacoes_reads %}
                <li class="d-flex" data-is-unread="{{notifi.unread}}" data-slug="{{notifi.slug}}">
                    {{ notifi|shownotify }} 
                    <button class="btn-close me-1" aria-label="Delete" onclick="deleteNotification(this)"></button>
                </li>
                {% endfor %} {% endif %}
            </ul>
        </div>{% endwith %}

        <div class="btn-group">
            <button type="button" class="fu-user" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.username|first|capfirst }}
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li>
                    <a href="{% url 'forum:logout' %}" class="dropdown-item text-danger">
                        <img width="20px" height="20px" src="{% static 'site_forum/icon/logout.svg'%}"/>
                        Sair
                    </a>
                </li>
            </ul>
        </div>
        {% else %}
        <div class="d-flex align-content-center">
            <a href="{% url 'forum:login' %}?next={{request.path}}" class="btn-entrar">Entrar</a>
        </div>
        {% endif %}
    </div>
</header>

site_forum/templates/site_forum/base/login_modal.html
{# ======== Modal LOGIN REQUERIDO ========#}
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginModalLabel">Login necessário</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-center">
        <p>Para executar essa ação você precisa entrar na sua conta!</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary" href="{% url 'forum:login' %}?next={{request.path}}">Entrar</a>
        <a class="btn btn-success" href="{% url 'forum:register'%}">Cadastrar-se</a>
      </div>
    </div>
  </div>
</div>

site_forum/templates/site_forum/base/messages.html
{% if messages %}
{% for message in messages %}
    {% if message.tags == 'sucess' %}
    <div class="alert alert-sucess" role="alert">{{message}}</div>

    {% elif message.tags == 'info' %}
    <div class="alert alert-info" role="alert">{{message}}</div>
    
    {% elif message.tags == 'warning' %}
    <div class="alert alert-warning" role="alert">{{message}}</div>
    
    {% elif message.tags == 'error' %}
    <div class="alert alert-danger" role="alert">{{message}}</div>
    
    {% elif message.tags == 'debug' %}
    <div class="alert alert-primary" role="alert">{{message}}</div>
    {% endif %}
{% endfor%}
{% endif %}